### ISSUE TITLE
stucked on `Invalid or missing API key`

### ISSUE THREAD

**Issue by NewJerseyStyle** [kcolemangt/llm-router#2]
I get same result on both MacOS and Ubuntu 20.04

Setup:
```bash
chmod +x llm-router-linux-amd64
OPENAI_API_KEY=ollama ./llm-router-linux-amd64
# OPENAI_API_KEY=ollama ./llm-router-darwin-arm64
```

On MacOS I set cursor editor URL for OpenAI API with `localhost` and key `ollama`, it is able to access but logging `Invalid or missing API key` in console

On Ubuntu I followed `ngrok http 11411` and cursor editor URL OpenAI API with `https://xxxx.ngrok-free.app/v1` and key `ollama`, again getting `Invalid or missing API key` in console

Logs
```
{"level":"warn","ts":1721764959.305944,"caller":"config/config.go:33","msg":"Config file not found, using default configuration","file":"config.json"}
2024/07/23 20:02:39 Starting server on :11411
{"level":"warn","ts":1721764977.5750027,"caller":"handler/handler.go:23","msg":"Invalid or missing API key","receivedAuthHeader":"","expectedAuthHeader":"****** ******"}
```

`ngrok` logs
```
20:02:57.573 UTC OPTIONS /v1/chat/completions   401 Unauthorized
```

**Comment by kcolemangt** [comment]
You're seeing `Invalid or missing API key` error because llm-router forwards OpenAI model calls to OpenAI. Set Cursor to use an ollama model or provide a valid OpenAI API key.

**Comment by NewJerseyStyle** [comment]
Right, forgot to mention, I set model in Cursor as `phi3` and `ollama/phi3` but None of them work. I don't know what am I missing. ollama in CLI works fine, curl also shows ollama server is working.

I just tested `config.json`
```json
{
        "listening_port": 11411,
        "backends": [
                {
                        "name": "ollama",
                        "base_url": "http://localhost:11434",
                        "prefix": "ollama/"
                }
        ]
}
```
Disable all models in Cursor and set `ollama/phi3` gets
```
{"level":"warn","ts":1721764977.5750027,"caller":"handler/handler.go:23","msg":"Invalid or missing API key","receivedAuthHeader":"","expectedAuthHeader":"****** ******"}
```

**Comment by kcolemangt** [comment]
```
...
"receivedAuthHeader":"",
"expectedAuthHeader":"****** ******"
```

Set `OPENAI_API_KEY` key in Cursor.

Cursor might not save your key unless it's a functioning OpenAI key.

**Comment by NewJerseyStyle** [comment]
Fair enough, so I can skip setting the key in Cursor if I only want to use ollama or Groq right? And in case I want to use Groq, all I need to do is setting Groq API in llm-router =D

**Comment by kcolemangt** [comment]
Your ngrok endpoint is public, exposing llm-router/ollama. An API key is necessary for security ([README background](https://github.com/kcolemangt/llm-router#background), [CVE-2024-37032](https://nvd.nist.gov/vuln/detail/CVE-2024-37032)).

Ensure Cursor and llm-router use the same unguessable OPENAI_API_KEY for authentication. Note: Cursor may not save/use the key unless verifiable with OpenAI, even if not routing calls there.

**Comment by ShiinaRinne** [comment]
In my case, it seems that all requests will only carry `Authorization` after `OPENAI_API_KEY` verification is successful. 
So for the first time, I removed this code and added them back after confirming that the Cursor is available.
https://github.com/ShiinaRinne/llm-router/blob/f0d79e13145012c4de5a6333d5e959cfb30d29cf/handler/handler.go#L29-L36

And seems like due to CORS issues, it will trigger an OPTIONS request, and I need to handle it specifically.
https://github.com/ShiinaRinne/llm-router/blob/f0d79e13145012c4de5a6333d5e959cfb30d29cf/handler/handler.go#L19-L25

And I need to delete the `Origin` from the Header, otherwise it will cause 403 error
![image](https://github.com/user-attachments/assets/91752c5e-bab4-48f6-b417-1a72330e02c9)

https://github.com/ShiinaRinne/llm-router/blob/f0d79e13145012c4de5a6333d5e959cfb30d29cf/handler/handler.go#L28

**Comment by NewJerseyStyle** [comment]
Thanks all for your sharing.

I thought I have closed the issue. So I will close it now.

Wish you all the best.
